"""initial migration

Revision ID: 322ef101f3e9
Revises: 60167dcdf05a
Create Date: 2018-12-30 17:42:18.432054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322ef101f3e9'
down_revision = '60167dcdf05a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('is_banned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'is_banned')
    # ### end Alembic commands ###
