"""initial migration

Revision ID: 60167dcdf05a
Revises: 
Create Date: 2018-12-30 14:37:13.773867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60167dcdf05a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_banned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_banned')
    # ### end Alembic commands ###
