"""empty message

Revision ID: d45eccf310b2
Revises: 09f09d67eddb
Create Date: 2018-12-19 14:53:01.760011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd45eccf310b2'
down_revision = '09f09d67eddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='company')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'company', ['name'], unique=True)
    # ### end Alembic commands ###
